# Generated by Django 3.2.5 on 2021-07-17 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pergunta', models.CharField(max_length=200, verbose_name='Texto da pergunta')),
                ('data_publi', models.DateTimeField(verbose_name='data de publicação')),
            ],
        ),
        migrations.CreateModel(
            name='Respostas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_resposta', models.CharField(max_length=200, verbose_name='texto da pergunta')),
                ('votes', models.IntegerField(default=0, verbose_name='numero de votos para essa resposta')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquete.pergunta')),
            ],
        ),
    ]
