# Generated by Django 3.2.5 on 2021-07-17 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Respostas',
            new_name='Resposta',
        ),
    ]
