# Generated by Django 3.2.5 on 2021-07-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0002_alter_produto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristica',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='caracteristica',
            name='ingredientes',
            field=models.TextField(verbose_name='Ingredientes'),
        ),
        migrations.AlterField(
            model_name='preco',
            name='unidades',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='preco',
            name='valor',
            field=models.FloatField(verbose_name='Valor'),
        ),
    ]
