# Generated by Django 3.2.5 on 2021-07-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0003_auto_20210719_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristica',
            name='ingredientes',
            field=models.TextField(unique=True, verbose_name='Ingredientes'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('D', 'Doce'), ('S', 'salgado')], max_length=1, verbose_name='Tipo do produto'),
        ),
    ]
