# Generated by Django 3.2.5 on 2021-07-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0004_auto_20210719_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='preco',
            name='tipo',
            field=models.CharField(blank=True, choices=[('C', 'Congelado'), ('F', 'Frito')], max_length=1),
        ),
    ]
