# Generated by Django 3.2.5 on 2021-07-19 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0005_preco_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristica',
            name='produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cardapio.produto'),
        ),
    ]
