# Generated by Django 3.2.5 on 2021-07-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0006_alter_caracteristica_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristica',
            name='voto',
            field=models.IntegerField(default=0, verbose_name='numero de favritos'),
        ),
    ]
