# Generated by Django 3.2.5 on 2021-07-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0007_caracteristica_voto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caracteristica',
            name='voto',
        ),
        migrations.AddField(
            model_name='produto',
            name='voto',
            field=models.IntegerField(default=0, verbose_name='numero de favritos'),
        ),
    ]
